# Generated by Django 3.0.3 on 2021-02-04 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='detail',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
