# Generated by Django 3.0.3 on 2021-02-09 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='tagline',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
